# Generated by Django 5.0.6 on 2024-06-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_current_faculty_studentoffaculty_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentoffaculty',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
