# Generated by Django 5.0.6 on 2024-06-25 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_teacher_typeofgrades_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='value',
        ),
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.faculty'),
        ),
        migrations.AddField(
            model_name='grade',
            name='speciality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.speciality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
