# Generated by Django 5.0.6 on 2024-06-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_dayofweek_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayofweek',
            name='language',
        ),
    ]
