# Generated by Django 5.0.6 on 2024-06-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_dayofweek_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayofweek',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='dayofweek',
            name='name_kz',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayofweek',
            name='name_ru',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
