# Generated by Django 5.0.6 on 2024-06-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_name_dayofweek_name_en_dayofweek_name_kz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayofweek',
            name='name_kz',
        ),
        migrations.RemoveField(
            model_name='dayofweek',
            name='name_ru',
        ),
    ]
